services:
  - type: web
    name: ai-booking-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: FASTAPI_HOST
        value: 0.0.0.0
      - key: FASTAPI_PORT
        fromService:
          type: web
          name: ai-booking-backend
          property: port

  - type: web
    name: ai-booking-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/app_colored.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: API_BASE_URL
        fromService:
          type: web
          name: ai-booking-backend
          property: host
